version: "3.8"

services:
  traefik:
    image: docker.io/library/traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - "/var/run/podman/podman.sock:/var/run/docker.sock:ro"
    restart: always
